import localFont from "next/font/local";
import "./globals.css";

const geomanist = localFont({
  src: [
    {
      path: "../../public/fonts/GeomanistLight.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeomanistRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeomanistMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/GeomanistBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Biblioteca 3D Jamar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geomanist.className} `}>{children}</body>
    </html>
  );
}
